title: micro:bit microphone
hero_image: images/banner.png
description: Using the microphone to trigger an action
version: 4
listed: false
copyedit: false
last_tested: "2023-09-22"
steps:
  - title: Introduction
